<a href="https://colab.research.google.com/github/lovnishverma/iris-demo/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/lovnishverma/datasets

In [1]:
import pandas as pd


df = pd.read_csv("https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/Crop.csv")

In [2]:
# Encoding

from sklearn.preprocessing import LabelEncoder

In [4]:
df.head()

,N,P,K,ph,EC,S,Cu,Fe,Mn,Zn,B,label
0,143,69,217,5.9,0.58,0.23,10.20,116.35,59.96,54.85,21.29,pomegranate
1,170,36,216,5.9,0.15,0.28,15.69,114.20,56.87,31.28,28.62,pomegranate
2,158,66,219,6.8,0.34,0.20,15.29,65.87,51.81,57.12,27.59,pomegranate
3,133,45,207,6.4,0.94,0.21,8.48,103.10,43.81,68.50,47.29,pomegranate
4,132,48,218,6.7,0.54,0.19,5.59,63.40,56.40,46.71,31.04,pomegranate

In [7]:
df.columns

Index(['N', 'P', 'K', 'ph', 'EC', 'S', 'Cu', 'Fe', 'Mn', 'Zn', 'B', 'label'], dtype='object')

In [8]:
df[['N', 'P', 'K', 'ph', 'EC', 'S', 'Cu', 'Fe', 'Mn', 'Zn', 'B']].cov()

,N,P,K,ph,EC,S,Cu,Fe,Mn,Zn,B
N,1011.754117,-51.539593,473.892243,7.816420,-6.113923,-15.362446,-3.589372,412.973025,760.814797,-9.677261,-140.350111
P,-51.539593,608.783457,1029.306126,0.735733,3.187508,-6.973785,-59.315779,-97.841886,-4520.104353,1.847925,113.521577
K,473.892243,1029.306126,6607.378026,15.500216,18.808802,-15.895468,-103.807944,-62.828922,-11463.401157,-144.784877,-504.527539
ph,7.816420,0.735733,15.500216,0.481334,-0.135301,-0.047407,0.051308,19.109479,21.255853,-1.071301,-3.226248
EC,-6.113923,3.187508,18.808802,-0.135301,0.406042,0.247070,0.374883,-13.526053,-34.546919,-1.213934,-3.228963
S,-15.362446,-6.973785,-15.895468,-0.047407,0.247070,33.355112,-5.584080,-35.811113,-10.258253,-0.728304,-4.374429
Cu,-3.589372,-59.315779,-103.807944,0.051308,0.374883,-5.584080,41.488417,84.472097,1057.657428,-23.407094,-40.513779
Fe,412.973025,-97.841886,-62.828922,19.109479,-13.526053,-35.811113,84.472097,3940.725622,8190.461516,-255.043599,-61.205298
Mn,760.814797,-4520.104353,-11463.401157,21.255853,-34.546919,-10.258253,1057.657428,8190.461516,116963.174632,-1285.646632,-1455.928825
Zn,-9.677261,1.847925,-144.784877,-1.071301,-1.213934,-0.728304,-23.407094,-255.043599,-1285.646632,133.260959,75.439790
B,-140.350111,113.521577,-504.527539,-3.226248,-3.228963,-4.374429,-40.513779,-61.205298,-1455.928825,75.439790,385.590052

In [10]:
df[['N', 'P', 'K', 'ph', 'EC', 'S', 'Cu', 'Fe', 'Mn', 'Zn', 'B']].corr()

,N,P,K,ph,EC,S,Cu,Fe,Mn,Zn,B
N,1.000000,-0.065671,0.183285,0.354199,-0.301646,-0.083626,-0.017519,0.206822,0.069939,-0.026355,-0.224705
P,-0.065671,1.000000,0.513214,0.042980,0.202738,-0.048939,-0.373229,-0.063169,-0.535664,0.006488,0.234306
K,0.183285,0.513214,1.000000,0.274853,0.363129,-0.033859,-0.198268,-0.012313,-0.412358,-0.154297,-0.316088
ph,0.354199,0.042980,0.274853,1.000000,-0.306050,-0.011831,0.011482,0.438771,0.089584,-0.133763,-0.236816
EC,-0.301646,0.202738,0.363129,-0.306050,1.000000,0.067136,0.091337,-0.338141,-0.158526,-0.165028,-0.258056
S,-0.083626,-0.048939,-0.033859,-0.011831,0.067136,1.000000,-0.150109,-0.098775,-0.005194,-0.010924,-0.038572
Cu,-0.017519,-0.373229,-0.198268,0.011482,0.091337,-0.150109,1.000000,0.208911,0.480128,-0.314798,-0.320314
Fe,0.206822,-0.063169,-0.012313,0.438771,-0.338141,-0.098775,0.208911,1.000000,0.381501,-0.351945,-0.049652
Mn,0.069939,-0.535664,-0.412358,0.089584,-0.158526,-0.005194,0.480128,0.381501,1.000000,-0.325646,-0.216797
Zn,-0.026355,0.006488,-0.154297,-0.133763,-0.165028,-0.010924,-0.314798,-0.351945,-0.325646,1.000000,0.332802
B,-0.224705,0.234306,-0.316088,-0.236816,-0.258056,-0.038572,-0.320314,-0.049652,-0.216797,0.332802,1.000000

# Encoding

## Label Encoding

* Suitable for ordinal (ranked) categories

**PPT:** https://github.com/lovnishverma/Slidespptspdfs/blob/main/Data%20Science/Python%20Basics%20Refresher.pdf

In [5]:
df['label'].value_counts()

label
pomegranate    104
mango          104
grapes         104
mulberry       104
ragi           104
potato         100
Name: count, dtype: int64

In [15]:
le = LabelEncoder()

df['label'] = le.fit_transform(df['label'])

In [12]:
df.head()

     N   P    K   ph    EC     S     Cu      Fe     Mn     Zn      B  label
0  143  69  217  5.9  0.58  0.23  10.20  116.35  59.96  54.85  21.29      3
1  170  36  216  5.9  0.15  0.28  15.69  114.20  56.87  31.28  28.62      3
2  158  66  219  6.8  0.34  0.20  15.29   65.87  51.81  57.12  27.59      3
3  133  45  207  6.4  0.94  0.21   8.48  103.10  43.81  68.50  47.29      3
4  132  48  218  6.7  0.54  0.19   5.59   63.40  56.40  46.71  31.04      3

In [16]:
df['label'].value_counts()

label
3    104
1    104
0    104
2    104
5    104
4    100
Name: count, dtype: int64

In [13]:
# decode

df['label'] = le.inverse_transform(df['label'])

In [14]:
df.head()

,N,P,K,ph,EC,S,Cu,Fe,Mn,Zn,B,label
0,143,69,217,5.9,0.58,0.23,10.20,116.35,59.96,54.85,21.29,pomegranate
1,170,36,216,5.9,0.15,0.28,15.69,114.20,56.87,31.28,28.62,pomegranate
2,158,66,219,6.8,0.34,0.20,15.29,65.87,51.81,57.12,27.59,pomegranate
3,133,45,207,6.4,0.94,0.21,8.48,103.10,43.81,68.50,47.29,pomegranate
4,132,48,218,6.7,0.54,0.19,5.59,63.40,56.40,46.71,31.04,pomegranate

# One-Hot Encoding
• Creates binary columns for each category.
• Suitable for nominal (unordered) categories.

https://github.com/lovnishverma/Slidespptspdfs/blob/main/Web%20Scraping/Web%20Scraping%20New.pdf

https://github.com/lovnishverma/Slidespptspdfs/blob/main/Web%20Scraping/webscraping%20old.pdf

https://github.com/lovnishverma/web_scraping

https://github.com/lovnishverma/iris-demo

# Try Solving Regression problem

**Using Linear Regression**

Evaluation Meterics:

* MSE
* RMSE
* R2 Score

https://github.com/lovnishverma/Python-Getting-Started